controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - camera_arm_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
